## https://github.com/facebookresearch/hydra/issues/910
# Not changing the working directory
run:
  dir: .
sweep:
  dir: .
  subdir: .

# Not saving the .hydra directory
output_subdir: null

job:
  env_set:
    WANDB_START_METHOD: thread
    WANDB_DIR: ${oc.env:PROJECT_ROOT}

defaults:
  # Disable hydra logging configuration, otherwise the basicConfig does not have any effect
  - override job_logging: none
  - override hydra_logging: none
