# metadata specialised for each experiment
core:
  version: 0.0.1
  tags:
    - mytag

defaults:
  - data: default_data
  - hydra: default_hydra
  - logging: default_logging
  - model: default_model
  - optim: default_optim
  - train: default_train
#  - hydra/launcher: joblib
