data:
  _target_: src.data.datamodule.MyDataModule

  datasets:
    train:
      _target_: src.data.dataset.MyDataset

#    val:
#      - _target_: src.data.dataset.MyDataset

    test:
      - _target_: src.data.dataset.MyDataset

  num_workers:
    train: 8
    val: 4
    test: 4

  batch_size:
    train: 32
    val: 16
    test: 16

  # example
  val_percentage: 0.1

module:
  _target_: src.modules.model.MyModel

  optimizer:
    #  Adam-oriented deep learning
    _target_: torch.optim.Adam
    #  These are all default parameters for the Adam optimizer
    lr: 0.001
    betas: [ 0.9, 0.999 ]
    eps: 1e-08
    weight_decay: 0

  lr_scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
    T_0: 10
    T_mult: 2
    eta_min: 0 # min value for the lr
    last_epoch: -1
    verbose: True
