run:
  dir: ${oc.env:PROJECT_ROOT}/.cache/${now:%Y-%m-%d}/${now:%H-%M-%S}

sweep:
  dir: ${oc.env:PROJECT_ROOT}/.cache/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  subdir: ${hydra.job.num}_${hydra.job.id}

job:
  env_set:
    WANDB_START_METHOD: thread
    WANDB_DIR: ${oc.env:PROJECT_ROOT}

defaults:
  # Disable hydra logging configuration, otherwise the basicConfig
  # does not have any effect
  - override job_logging: none
  - override hydra_logging: none
